### PR TITLE
Allow multiple blockly tabs

### PR DESCRIPTION
**Pull request by BrettASwift**
@kadst43 

Allows mutliple tabs to be enabled. I didn't do it for all scenarios, just one to test. Remember: the first node in the list will be set as the active one.

### CODE REVIEW

**Comment by kadst43** [comment]
@AmbientOSX: Could you (or Jonatan) use this to re-enable the graph tab in M2?

**Comment by BrettASwift** [comment]
I will make the changes and update the PR.

**Comment by BrettASwift** [comment]
I added the graph tab to all of the scenarios in mission 2 that you are moving the rover in so you can refer to the graph tab if needed. I did not add the rover tab to the scenarios where you need only the graph.

**Comment by kadst43** [comment]
Sounds good.  We'll try it like this, and I see how to tweak it if I need to.

:+1:

**Pull request merged**
