### PR TITLE
Art drop

### PR DESCRIPTION
**Pull request by BrettASwift**
@kadst43 @AmbientOSX 

This has updated assets for the intro video as well as mission 1 and 3 success videos. It also has updated mini rover tracks and the cargo pod. I still have to add the cargo pod switching models after the video plays.

I also accidentally included an update to make the objective text more readable. I changed the text color to a very light blue and added a black drop shadow. It seems fairly readable to me, now. Let me know what you think.

### CODE REVIEW

**Comment by AmbientOSX** [comment]
:+1:

**Comment by kadst43** [comment]
:+1:

**Comment by kadst43** [comment]
(PS: let's try not to leave PRs laying around this long if we can help it...)

**Comment by BrettASwift** [comment]
Sorry, this is in progress, I'll update it soon.

**Comment by BrettASwift** [comment]
I managed to get most of my changes in here after resetting my branch and re-adding all of the commits apart from the perry texture change, which was causing the issue with my current configuration.

This branch contains:
- New videos for mission 1 and 3 success as well as intro video
- New mini rover tracks
- More readable objective text
- Changed "Switch Scenario" to "Load Mission"
- Moved callout tile and functionality to shader
- [WIP] Started rover position HUD Element (commented out, will complete in another branch)
- [WIP] Assets for open and closed crash pod (will complete in another branch)

I'll wait for final approval before merging.

**Comment by kadst43** [comment]
:+1:

**Pull request merged**
